  //Example instantiation for system 'TRANS_3'
  TRANS_3 TRANS_3_inst
    (
      .bidir_port_to_and_from_the_pio_c1_data  (bidir_port_to_and_from_the_pio_c1_data),
      .bidir_port_to_and_from_the_pio_c2_data  (bidir_port_to_and_from_the_pio_c2_data),
      .bidir_port_to_and_from_the_pio_data_24  (bidir_port_to_and_from_the_pio_data_24),
      .bidir_port_to_and_from_the_pio_sda_9557 (bidir_port_to_and_from_the_pio_sda_9557),
      .clk_0                                   (clk_0),
      .data0_to_the_epcs_flash_controller_0    (data0_to_the_epcs_flash_controller_0),
      .dclk_from_the_epcs_flash_controller_0   (dclk_from_the_epcs_flash_controller_0),
      .in_port_to_the_pio_c1_dr                (in_port_to_the_pio_c1_dr),
      .in_port_to_the_pio_c2_dr                (in_port_to_the_pio_c2_dr),
      .out_port_from_the_pio_c1_ce             (out_port_from_the_pio_c1_ce),
      .out_port_from_the_pio_c1_clk            (out_port_from_the_pio_c1_clk),
      .out_port_from_the_pio_c1_cs             (out_port_from_the_pio_c1_cs),
      .out_port_from_the_pio_c2_ce             (out_port_from_the_pio_c2_ce),
      .out_port_from_the_pio_c2_clk            (out_port_from_the_pio_c2_clk),
      .out_port_from_the_pio_c2_cs             (out_port_from_the_pio_c2_cs),
      .out_port_from_the_pio_clk_24            (out_port_from_the_pio_clk_24),
      .out_port_from_the_pio_led1              (out_port_from_the_pio_led1),
      .out_port_from_the_pio_led2              (out_port_from_the_pio_led2),
      .out_port_from_the_pio_led3              (out_port_from_the_pio_led3),
      .out_port_from_the_pio_reset_9557        (out_port_from_the_pio_reset_9557),
      .out_port_from_the_pio_scl_9557          (out_port_from_the_pio_scl_9557),
      .reset_n                                 (reset_n),
      .rxd_to_the_uart_usb                     (rxd_to_the_uart_usb),
      .sce_from_the_epcs_flash_controller_0    (sce_from_the_epcs_flash_controller_0),
      .sdo_from_the_epcs_flash_controller_0    (sdo_from_the_epcs_flash_controller_0),
      .txd_from_the_uart_usb                   (txd_from_the_uart_usb),
      .zs_addr_from_the_sdram_0                (zs_addr_from_the_sdram_0),
      .zs_ba_from_the_sdram_0                  (zs_ba_from_the_sdram_0),
      .zs_cas_n_from_the_sdram_0               (zs_cas_n_from_the_sdram_0),
      .zs_cke_from_the_sdram_0                 (zs_cke_from_the_sdram_0),
      .zs_cs_n_from_the_sdram_0                (zs_cs_n_from_the_sdram_0),
      .zs_dq_to_and_from_the_sdram_0           (zs_dq_to_and_from_the_sdram_0),
      .zs_dqm_from_the_sdram_0                 (zs_dqm_from_the_sdram_0),
      .zs_ras_n_from_the_sdram_0               (zs_ras_n_from_the_sdram_0),
      .zs_we_n_from_the_sdram_0                (zs_we_n_from_the_sdram_0)
    );

