#!/bin/sh
#
# This file was automatically generated by the Nios II IDE Flash Programmer.
#
# It will be overwritten when the flash programmer options change.
#

cd G:/Quartus/transfer_new/trans_3/Debug

# Creating .flash file for the FPGA configuration
"$SOPC_KIT_NIOS2/bin/sof2flash" --epcs --input="G:/Quartus/transfer_new/TRANS_CL3.sof" --output="TRANS_CL3.flash" 

# Programming flash with the FPGA configuration
"$SOPC_KIT_NIOS2/bin/nios2-flash-programmer" --epcs --base=0x01001800 --sidp=0x01002188 --id=364094772 --timestamp=1426599870  "TRANS_CL3.flash"

# Creating .flash file for the project
"$SOPC_KIT_NIOS2/bin/elf2flash" --epcs --after="TRANS_CL3.flash" --input="trans_3.elf" --output="epcs_flash_controller_0.flash"

# Programming flash with the project
"$SOPC_KIT_NIOS2/bin/nios2-flash-programmer" --epcs --base=0x01001800 --sidp=0x01002188 --id=364094772 --timestamp=1426599870  "epcs_flash_controller_0.flash"

